### PR TITLE
feat: add toggle password visibility

### PR DESCRIPTION
**Pull request by vatana7**
PR for https://github.com/invisal/query-master/issues/109

@invisal Please review and give feedback

### CODE REVIEW

**Comment by vatana7** [comment]
@invisal Please review and give feedback

**Review by invisal — COMMENTED** [review]
I recommend you to create another component called `PasswordField`. 

In the TextField file, we can split the interface

```
export interface TextFieldCommonProps {
  readOnly?: boolean;
  onChange?: (value: string) => void;
  label?: string;
  value?: string;
  autoFocus?: boolean;
  placeholder?: string;
}

interface TextFieldProps extends TextFieldCommonProps  {
  multipleLine?: boolean;
  type?: 'text' | 'password';
  actionIcon?: ReactElement;
  actionClick?: () => void;
}
```

The common PasswordField can use the existing TextField. Maybe something like this

```
function PasswordField(props: TextFieldCommonProps) {
  // handle toggle logic here
  
  return <TextField {...props} actionIcon={...} actionClick={() => ...} />
  
}
```

For state, you don't to use generic state as there is only one state at the moment.

**Comment by vatana7** [comment]
@invisal i've changed the code as you suggested

**Review by invisal — APPROVED** [review]
LGTM

**Pull request merged**
