### PR TITLE
[WIP] feat: error panel

### PR DESCRIPTION
**Pull request by thormengkheang**

### CODE REVIEW

**Comment by invisal** [comment]
I believe we should just use our QueryMultipleResultViewer. When there is error, it should show one error tab. For example:

```
SELECT * FROM hello LIMIT 10;
SELECT * FROM hello WHERE LIMIT 10;
```

As you can see, the error is on the second statements. But we should multiple statement result. In this case, it should show two tabs. One is the result of the first statement and second is the error message of the second statement.

```
SELECT * FROM hello WHERE LIMIT 10;
```

For case of a single statement, it should just show the error message.

**Comment by rin-yato** [comment]
What if the user want to revert on error?

**Comment by invisal** [comment]
> What if the user want to revert on error?

What do you mean revert on error?

**Comment by rin-yato** [comment]
> > What if the user want to revert on error?
> 
> What do you mean revert on error?

They have 2 statements the last one will cause an error. Will the first one run, or will it not run? What if the user want to the first statement to not run if there is error on the second statement

**Comment by invisal** [comment]
> > > What if the user want to revert on error?
> > 
> > 
> > What do you mean revert on error?
> 
> They have 2 statements the last one will cause an error. Will the first one run, or will it not run? What if the user want to the first statement to not run if there is error on the second statement

It is not possible to determine if the second one run without running the first one. Since we need to send both to the server for server to determine.

**Comment by thormengkheang** [comment]
> I believe we should just use our QueryMultipleResultViewer. When there is error, it should show one error tab. For example:
> 
> ```
> SELECT * FROM hello LIMIT 10;
> SELECT * FROM hello WHERE LIMIT 10;
> ```
> 
> As you can see, the error is on the second statements. But we should multiple statement result. In this case, it should show two tabs. One is the result of the first statement and second is the error message of the second statement.
> 
> ```
> SELECT * FROM hello WHERE LIMIT 10;
> ```
> 
> For case of a single statement, it should just show the error message.

I see let me work on that.

**Pull request closed without merging**
